# Generated by Django 5.0.6 on 2024-07-15 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_lecturer_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturers', to='apps.program'),
        ),
    ]
