# Generated by Django 5.0.6 on 2024-07-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
